[package]
name = "quantumix_model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
surrealdb = { version = "1.5.0", default-features = false }
