name: Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.lock"
      - "**/Cargo.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Rust Audit (Server)
        uses: actions-rust-lang/audit@v1
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./server/

      - name: Run Rust Audit (Client)
        uses: actions-rust-lang/audit@v1
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./src-tauri/

      - name: Run Rust Audit (Server)
        uses: actions-rust-lang/audit@v1
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./model/
