name: Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.lock"
      - "**/Cargo.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Workspace
        run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE/server" >> $GITHUB_ENV

      - name: Run Audit Check
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
