name: PR Verification

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-win64:
    runs-on: windows-latest
    if: github.event.comment.body == 'run tests'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cargo fmt -- --check

      - name: Test Project
        run: |
          cargo check
          cargo test --all

  test-linux:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'run tests'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cargo fmt -- --check

      - name: Test Project
        run: |
          cargo check
          cargo test --all