name: PR Verification

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win64-debug:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Set up downstream repository secrets
        run: echo "GH_TOKEN=${{ secrets.QUANTUMIX_TOKEN }}" >> $GITHUB_ENV

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cd .
          cargo fmt -- --check

      - name: Test Project
        run: |
          cargo check
          cargo test --all

  build-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Set up downstream repository secrets
        run: echo "GH_TOKEN=${{ secrets.QUANTUMIX_TOKEN }}" >> $GITHUB_ENV

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cd .
          ls
          cargo fmt -- --check

      - name: Test Project
        run: |
          cargo check
          cargo test --all