name: PR Verification

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  test-win64:
    runs-on: windows-latest
    steps:
      - name: Check if PR comment contains 'run tests'
        id: check_comment
        run: echo ::set-output name=run_tests::$(echo "${{ github.event.comment.body }}" | grep -c 'run tests')

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cargo fmt -- --check

      - name: Test Project
        if: steps.check_comment.outputs.run_tests == '1'
        run: |
          cargo check
          cargo test --all

   test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR comment contains 'run tests'
        id: check_comment
        run: echo ::set-output name=run_tests::$(echo "${{ github.event.comment.body }}" | grep -c 'run tests')

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.QUANTUMIX_TOKEN }}

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Lint Code
        run: |
          cargo fmt -- --check

      - name: Test Project
        run: |
          cargo check
          cargo test --all