name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update     
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Lint Code
        run: |
          cd .
          # cargo fmt -- --check
          
      - name: Test and Build
        env:
          GH_TOKEN: ${{ secrets.QUANTUMIX_TOKEN }}
        run: |
          cd .

          # Install oblivion
          git clone --depth 1 https://${GH_TOKEN}@github.com/noctisynth/oblivion-rust.git
          cargo install --path oblivion-rust
          source $HOME/.cargo/env

          cargo check
          cargo test --all    
          
          cargo build --release
