name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update     
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Lint Code
        run: |
          cd .
          # cargo fmt -- --check

      - name: Install Oblivion
        env:
          GH_TOKEN: ${{ secrets.QUANTUMIX_TOKEN }}
        run: |
          cd .
          git clone --depth 1 https://${GH_TOKEN}@github.com/noctisynth/oblivion-rust.git
          mv oblivion-rust oblivion
          ls

      - name: Test Project
        run: |
          cargo check
          cargo test --all    
      - name: Build Quantumix-Server
        run: |
          cargo build --release
